# Generated by Django 5.2.7 on 2025-10-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="crops/"),
        ),
    ]
